# Site Settings
title: Nicholas Dean
url: 'http://www.nicholasadean.com'
baseurl: '' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
style: styles-6

#Profile information
name: Nicholas Dean
tagline: 
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'SaaS professional specializing in system implementation, administration, and process improvement.'

#sidebar links
email: nick@nicholasadean.com
website: nicholasadean.com #do not add http://
linkedin: nicholasdean
#github: ''
twitter: monvoix
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-115988100-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
